baseURL = "/"
languageCode = "es-es"
title = "Links Profesionales para Networking"
theme = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Enlaces profesionales para networking y herramientas útiles"
  author = "Tu Nombre"
  mainColor = "#2E5090"
  secondaryColor = "#F5F5F5"
  profileImage = "https://via.placeholder.com/150"
