baseURL = "/"
languageCode = "es"
title = "Networking Professional Links"
# Eliminar la línea de theme vacía o configurar correctamente
disableKinds = ["taxonomy", "term"]

[params]
  description = "Herramientas profesionales para networking"
  author = "Networking Professional"
  mainImage = "/images/profile-image.jpg"
  favicon = "/images/favicon.png"
